# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_course_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(upload_to='courses/'),
        ),
    ]
