# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20170921_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/'),
        ),
    ]
